// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `with_db`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DB`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `from`, `from`, `from`, `initialize`

Future<void> initDb({required String appDocDir}) =>
    RustLib.instance.api.crateApiNativeInitDb(appDocDir: appDocDir);

Future<List<Note>> getAllNotes() =>
    RustLib.instance.api.crateApiNativeGetAllNotes();

Future<Note> createNote({
  required String title,
  required String content,
  String? folder,
}) => RustLib.instance.api.crateApiNativeCreateNote(
  title: title,
  content: content,
  folder: folder,
);

Future<Note> updateNote({
  required String id,
  required String title,
  required String content,
  String? folder,
  required bool isPinned,
}) => RustLib.instance.api.crateApiNativeUpdateNote(
  id: id,
  title: title,
  content: content,
  folder: folder,
  isPinned: isPinned,
);

Future<void> deleteNote({required String id}) =>
    RustLib.instance.api.crateApiNativeDeleteNote(id: id);

Future<void> restoreNote({required String id}) =>
    RustLib.instance.api.crateApiNativeRestoreNote(id: id);

Future<UserSettings> getSettings() =>
    RustLib.instance.api.crateApiNativeGetSettings();

Future<void> updateSettings({required UserSettings settings}) =>
    RustLib.instance.api.crateApiNativeUpdateSettings(settings: settings);

class Note {
  final String id;
  final String title;
  final String content;
  final String? folder;
  final bool isPinned;
  final String createdAt;
  final String updatedAt;
  final int version;
  final bool isDeleted;

  const Note({
    required this.id,
    required this.title,
    required this.content,
    this.folder,
    required this.isPinned,
    required this.createdAt,
    required this.updatedAt,
    required this.version,
    required this.isDeleted,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      content.hashCode ^
      folder.hashCode ^
      isPinned.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      version.hashCode ^
      isDeleted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Note &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          content == other.content &&
          folder == other.folder &&
          isPinned == other.isPinned &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          version == other.version &&
          isDeleted == other.isDeleted;
}

class UserSettings {
  final String themeMode;
  final int accentHue;
  final String fontFamily;
  final int fontSize;

  const UserSettings({
    required this.themeMode,
    required this.accentHue,
    required this.fontFamily,
    required this.fontSize,
  });

  @override
  int get hashCode =>
      themeMode.hashCode ^
      accentHue.hashCode ^
      fontFamily.hashCode ^
      fontSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserSettings &&
          runtimeType == other.runtimeType &&
          themeMode == other.themeMode &&
          accentHue == other.accentHue &&
          fontFamily == other.fontFamily &&
          fontSize == other.fontSize;
}
